# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.ImageField(blank=True, default='head/memtx.png', upload_to='head/%Y%m', verbose_name='用户头像'),
        ),
    ]
