# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 10:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181127_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='harea',
            field=models.CharField(max_length=100, verbose_name='区'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='hcity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='hproper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='收货人手机号'),
        ),
    ]
