# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 13:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}', '手机号码格式错误')])),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
