# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='custom_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
