# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181128_1023'),
        ('goods', '0006_auto_20181127_1747'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='订单编号')),
                ('order_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='订单金额')),
                ('username', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='收货人电话')),
                ('address', models.CharField(max_length=255, verbose_name='收货人地址')),
                ('status', models.SmallIntegerField(choices=[(0, '待付款'), (1, '已付款'), (2, '待发货'), (3, '已发货'), (4, '待评价'), (5, '申请退款'), (6, '已退款'), (7, '完成'), (8, '取消订单')], default=0, verbose_name='订单状态')),
                ('transport', models.CharField(max_length=50, verbose_name='运输方式')),
                ('transport_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运费')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='实付金额')),
            ],
            options={
                'verbose_name': '订单基本信息管理',
                'verbose_name_plural': '订单基本信息管理',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('count', models.IntegerField(verbose_name='订单商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='订单商品价格')),
                ('goodsSku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSku', verbose_name='sku_id')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='订单商品id')),
            ],
            options={
                'verbose_name': '订单商品管理',
                'verbose_name_plural': '订单商品管理',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(max_length=50, verbose_name='支付方式')),
                ('img', models.ImageField(upload_to='pay/%Y', verbose_name='图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '支付管理',
                'verbose_name_plural': '支付管理',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Payment', verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='用户id'),
        ),
    ]
