# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'verbose_name': '轮播商品', 'verbose_name_plural': '轮播商品'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品sku', 'verbose_name_plural': '商品sku'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': '活动专区', 'verbose_name_plural': '活动专区'},
        ),
        migrations.AlterModelOptions(
            name='specialgoods',
            options={'verbose_name': '活动商品', 'verbose_name_plural': '活动商品'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='a_url',
            field=models.URLField(verbose_name='活动url地址'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='url',
            field=models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='goodsimg',
            name='url',
            field=models.ImageField(upload_to='goods_gallery/%Y%m/%d', verbose_name='相册图片地址'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='url',
            field=models.ImageField(upload_to='goods/%Y%m/%d', verbose_name='封面图片'),
        ),
    ]
