# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181123_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='简介'),
        ),
    ]
