# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181124_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='detail',
            field=models.TextField(verbose_name='详情'),
        ),
    ]
