# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 17:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20181124_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='详情'),
        ),
    ]
